// Spec — PDF SKELETON
// -----------------------------------------------------------------------------------------------
// A starting pdf.tsx for a designed Tier-1 spec, visually consistent with the other templates
// (full-bleed CoverPage + page-numbered ToC + sections). The Markdown twin is
// references/templates/markdown/spec.md, which is also the Tier-1 spec format contract (there is no
// separate spec-format doc).
// Copy this file to the render run dir as  <RUNDIR>/pdf.tsx , fill the DATA section, then render
// (run it from the using-doc-creation skill dir so tsx + the package resolve):
//
//   cd "${CLAUDE_PLUGIN_ROOT}/skills/using-doc-creation" \
//     && node --import tsx src/pdf/render.ts "<RUNDIR>"          # light by default; --theme dark for dark
//
// where <RUNDIR> is the absolute path printed by
//   sh "${CLAUDE_PLUGIN_ROOT}/scripts/run-context.sh" using-doc-creation <slug> --fresh
//
// DISCIPLINE:
//   • §0 ELI5 is written LAST, from the finished sections, but placed first. Jargon-free.
//   • §3 success criteria are OBSERVABLE — each with how it's checked (the table).
//   • §5 forces non-goals and a Deferred table; never park work silently.
//   • Status is Draft when written; the spec gate flips it to Approved on approval.
//   • The ToC lives in `frontMatter` (an UNNUMBERED page); fill its `page` values on a 2nd pass.
//   • This is the reader's document — no "generated by" line, no tool/skill attribution.
// This file COMPILES AND RENDERS AS-IS (placeholder copy) so you can preview before filling.
// -----------------------------------------------------------------------------------------------

import {
  PdfDoc,
  CoverPage,
  Toc,
  Section,
  P,
  B,
  Table,
  KeyBox,
  Mermaid,
  rasterizeMermaid,
  type PdfTheme,
} from '@engineering/using-doc-creation';

const R = String.raw;

// ===============================================================================================
// DATA — fill these in. The WIRING section below renders them.
// ===============================================================================================

const COVER = {
  eyebrow: 'Spec · <YYYY-MM-DD>',
  title: '<Title> — spec',
  subtitle: '<One plain-language sentence: what this spec proposes and why now.>',
  tags: ['Status: Draft', '<Origin: signal | triage>'],
  meta: [
    { label: 'Date', value: '<YYYY-MM-DD>' },
    { label: 'Author', value: '<name or @handle>' },
    { label: 'Status', value: 'Draft' },
    { label: 'Origin', value: '<signal (discovery) | triage (<ref>)>' },
  ],
};

// One row per section. `page` is BODY-relative (filled on pass 2). `link` jumps to the matching id.
const TOC: { title: string; page?: number | string; level?: 0 | 1; link?: string }[] = [
  { title: '0. ELI5', page: '—', link: 'eli5' },
  { title: '1. Problem', page: '—', link: 'problem' },
  { title: '2. Users & stakeholders', page: '—', link: 'users' },
  { title: '3. Goals & success criteria', page: '—', link: 'goals' },
  { title: '4. Constraints', page: '—', link: 'constraints' },
  { title: '5. Scope', page: '—', link: 'scope' },
  { title: '6. Approach', page: '—', link: 'approach' },
  { title: '7. Existing context', page: '—', link: 'context' },
  { title: '8. Open questions', page: '—', link: 'open-questions' },
];

const GOALS: string[][] = [
  ['<observable outcome>', '<the command, artifact, or observation that confirms it>'],
  ['<observable outcome>', '<how it is checked>'],
];

const DEFERRED: string[][] = [
  ['<parked work>', '<the condition that would bring it back into scope>'],
];

// OPTIONAL — a process-flow diagram for §6. Set to null to omit (no browser needed then).
const APPROACH_FLOW: string | null = R`flowchart TD
    In[Trigger] --> Choice{Decision}
    Choice -->|Path A| A[Outcome A]
    Choice -->|Path B| B[Outcome B]`;

// ===============================================================================================
// WIRING — no edits needed below for a standard spec.
// ===============================================================================================

export default async (theme: PdfTheme) => {
  const flow = APPROACH_FLOW ? await rasterizeMermaid(APPROACH_FLOW, theme) : null;

  return (
    <PdfDoc
      theme={theme}
      title={COVER.title}
      cover={
        <CoverPage
          eyebrow={COVER.eyebrow}
          title={COVER.title}
          subtitle={COVER.subtitle}
          tags={COVER.tags}
          meta={COVER.meta}
        />
      }
      frontMatter={
        <Section eyebrow="Contents" title="What's inside" deck="Each part of this spec, in order.">
          <Toc items={TOC} breakAfter={false} />
        </Section>
      }
    >
      <Section eyebrow="Summary" title="0. ELI5" id="eli5" deck="The whole spec in plain language.">
        <P>
          TODO — jargon-free: what's broken or missing, what we're going to do about it, and how we'll
          know it worked. Written LAST, from the sections below; placed first.
        </P>
      </Section>

      <Section eyebrow="Why" title="1. Problem" id="problem" deck="What we are solving and why now.">
        <P>TODO — the problem in a few sentences, and who feels it today.</P>
      </Section>

      <Section eyebrow="Who" title="2. Users &amp; stakeholders" id="users" deck="Who is affected; who decides.">
        <P>TODO — users, affected parties, and the sign-off (names or <B>@handles</B>, never personal emails).</P>
      </Section>

      <Section eyebrow="Done means" title="3. Goals &amp; success criteria" id="goals" deck="Observable outcomes, each checkable.">
        <Table head={['Criterion', "How it's checked"]} rows={GOALS} />
      </Section>

      <Section eyebrow="Limits" title="4. Constraints" id="constraints" deck="Hard limits and must-not-breaks.">
        <P>TODO — platforms, versions, dependencies, deadlines, non-negotiables.</P>
      </Section>

      <Section eyebrow="Boundary" title="5. Scope" id="scope" deck="What's in, what's out, what's parked.">
        <P><B>In.</B> TODO — the committed work.</P>
        <P><B>Out (non-goals).</B> TODO — each with a one-line reason.</P>
        <Table head={['Deferred item', 'Trigger to revive']} rows={DEFERRED} />
      </Section>

      <Section eyebrow="How" title="6. Approach" id="approach" deck="The approved approach and the alternatives.">
        <P>
          TODO — the chosen approach and what it beat. Where it turned on a boundary, name the boundary,
          its chosen shape, and what a caller must know. Increments, if any, as one ordered list.
        </P>
        {flow && <Mermaid diagram={flow} title="Approach" caption="TODO — what the diagram shows." />}
      </Section>

      <Section eyebrow="Landscape" title="7. Existing context" id="context" deck="What the work touches.">
        <P>TODO — relevant modules, prior art, systems this must fit into, and any docs consulted.</P>
      </Section>

      <Section eyebrow="Unresolved" title="8. Open questions" id="open-questions" deck="Anything unresolved that does not block starting.">
        <KeyBox role="accent" title="Open">
          TODO — list open questions, or state there are none. Empty is fine.
        </KeyBox>
      </Section>
    </PdfDoc>
  );
};
