// Plan — PDF SKELETON
// -----------------------------------------------------------------------------------------------
// A starting pdf.tsx for a designed implementation plan, visually consistent with the other
// templates (full-bleed CoverPage + page-numbered ToC + sections). The Markdown twin is
// references/templates/markdown/plan.md.
// Copy this file to the render run dir as  <RUNDIR>/pdf.tsx , fill the DATA section, then render
// (run it from the using-doc-creation skill dir so tsx + the package resolve):
//
//   cd "${CLAUDE_PLUGIN_ROOT}/skills/using-doc-creation" \
//     && node --import tsx src/pdf/render.ts "<RUNDIR>"          # light by default; --theme dark for dark
//
// DISCIPLINE:
//   • Global Constraints are copied VERBATIM from the spec's Constraints + binding decisions
//     (PR strategy, Finish strategy, Isolation) — downstream phases read them.
//   • One Task block per task, in dependency order. Each step names an exact file path and, where it
//     changes behavior, is wired into the TDD loop. Each task carries its own verification.
//   • Duplicate the Task section per task; the ToC row + Section id follow the same numbering.
//   • This is the reader's document — no "generated by" line, no tool/skill attribution.
// This file COMPILES AND RENDERS AS-IS (placeholder copy) so you can preview before filling.
// -----------------------------------------------------------------------------------------------

import {
  PdfDoc,
  CoverPage,
  Toc,
  Section,
  Subhead,
  P,
  B,
  Table,
  Checklist,
  KeyBox,
  type PdfTheme,
} from '@engineering/using-doc-creation';

// ===============================================================================================
// DATA — fill these in. The WIRING section below renders them.
// ===============================================================================================

const COVER = {
  eyebrow: 'Plan · <YYYY-MM-DD>',
  title: '<Title> — plan',
  subtitle: '<One sentence: what this plan builds, from which approved spec.>',
  tags: ['PR: <single | stacked>', 'Isolation: <worktree | feature-branch>'],
  meta: [
    { label: 'Date', value: '<YYYY-MM-DD>' },
    { label: 'Author', value: '<name or @handle>' },
    { label: 'Spec', value: '<path to approved spec>' },
    { label: 'Finish', value: 'pull request' },
  ],
};

const TOC: { title: string; page?: number | string; level?: 0 | 1; link?: string }[] = [
  { title: 'Global Constraints', page: '—', link: 'constraints' },
  { title: 'Task 1 — <task title>', page: '—', link: 'task-1' },
  { title: 'Done when', page: '—', link: 'done' },
];

// The binding constraints, copied verbatim from the spec's §4 + decisions.
const CONSTRAINTS: string[] = [
  '<constraint copied verbatim from the spec>',
  'PR strategy: <single-branch | stacked (one PR per task)>',
  'Finish strategy: pull request',
  'Isolation: <worktree | feature-branch>',
];

// One entry per Task. Duplicate the Section in WIRING for each.
const TASK1_STEPS = [
  { text: '<Create|Modify>: <path/to/file.ext> — the change' },
  { text: 'Write the failing test first (where behavior changes): <test path>; run it, confirm red' },
  { text: 'Implement the minimum to pass; run the test, confirm green' },
  { text: 'Verify with the command below; commit' },
];

// ===============================================================================================
// WIRING — duplicate the Task section per task.
// ===============================================================================================

export default (theme: PdfTheme) => (
  <PdfDoc
    theme={theme}
    title={COVER.title}
    cover={
      <CoverPage
        eyebrow={COVER.eyebrow}
        title={COVER.title}
        subtitle={COVER.subtitle}
        tags={COVER.tags}
        meta={COVER.meta}
      />
    }
    frontMatter={
      <Section eyebrow="Contents" title="What's inside" deck="Global constraints, then each task, in order.">
        <Toc items={TOC} breakAfter={false} />
      </Section>
    }
  >
    <Section eyebrow="Binding" title="Global Constraints" id="constraints" deck="Copied verbatim from the spec; every task points back here.">
      <P>
        TODO — the spec's §4 constraints and binding decisions, so each task reads &quot;per Global
        Constraints, this uses <B>X</B>&quot; rather than restating it.
      </P>
      <Checklist items={CONSTRAINTS.map((text) => ({ text, done: false }))} />
    </Section>

    <Section eyebrow="Task 1" title="Task 1 — <task title>" id="task-1" deck="One-line intent. Duplicate this section per task.">
      <Checklist items={TASK1_STEPS} />
      <Subhead title="Verification" />
      <P>TODO — the command this task's steps run, and the output that counts as passing.</P>
      <KeyBox role="accent" title="Interfaces (only if the task adds/reshapes a boundary)">
        TODO — a short sketch of the signature / type the task produces, or delete this box.
      </KeyBox>
    </Section>

    <Section eyebrow="Definition of done" title="Done when" id="done" deck="The observable end state.">
      <Table
        head={['Check', 'How it is confirmed']}
        rows={[
          ['<every task box checked>', '<the plan file shows all tasks complete>'],
          ['<suite green>', '<the verification command and its passing output>'],
        ]}
      />
    </Section>
  </PdfDoc>
);
